-- Database online untuk ABSEN MASKANA
-- Jalankan seluruh script ini di Supabase > SQL Editor > New query.

create table if not exists public.participants (
  id text primary key,
  name text not null,
  phone text default '',
  village text not null default '',
  district text not null default '',
  regency text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  participant_id text not null references public.participants(id) on delete cascade,
  time timestamptz not null default now(),
  constraint attendance_one_per_participant unique (participant_id)
);

create index if not exists participants_village_idx on public.participants (village);
create index if not exists attendance_time_idx on public.attendance (time desc);

-- Aktifkan Row Level Security.
alter table public.participants enable row level security;
alter table public.attendance enable row level security;

-- Karena versi awal aplikasi belum memakai login admin, perangkat menggunakan
-- role anon. Kebijakan ini membuat aplikasi bisa dipakai bersama.
-- Untuk produksi yang lebih ketat, nanti kita bisa menambahkan login admin.
drop policy if exists "participants_public_select" on public.participants;
drop policy if exists "participants_public_insert" on public.participants;
drop policy if exists "participants_public_update" on public.participants;
drop policy if exists "participants_public_delete" on public.participants;

create policy "participants_public_select"
  on public.participants for select to anon, authenticated using (true);
create policy "participants_public_insert"
  on public.participants for insert to anon, authenticated with check (true);
create policy "participants_public_update"
  on public.participants for update to anon, authenticated using (true) with check (true);
create policy "participants_public_delete"
  on public.participants for delete to anon, authenticated using (true);

drop policy if exists "attendance_public_select" on public.attendance;
drop policy if exists "attendance_public_insert" on public.attendance;
drop policy if exists "attendance_public_update" on public.attendance;
drop policy if exists "attendance_public_delete" on public.attendance;

create policy "attendance_public_select"
  on public.attendance for select to anon, authenticated using (true);
create policy "attendance_public_insert"
  on public.attendance for insert to anon, authenticated with check (true);
create policy "attendance_public_update"
  on public.attendance for update to anon, authenticated using (true) with check (true);
create policy "attendance_public_delete"
  on public.attendance for delete to anon, authenticated using (true);

-- Beri akses Data API ke role yang dipakai browser.
grant select, insert, update, delete on public.participants to anon, authenticated;
grant select, insert, update, delete on public.attendance to anon, authenticated;
grant usage, select on sequence public.attendance_id_seq to anon, authenticated;

-- Aktifkan Realtime untuk kedua tabel.
do $$
begin
  alter publication supabase_realtime add table public.participants;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.attendance;
exception when duplicate_object then null;
end $$;

-- Pastikan perubahan baris lengkap dikirim oleh Realtime.
alter table public.participants replica identity full;
alter table public.attendance replica identity full;
